wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1691810997.556686
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.17
      5: 0.15.8
      8:
      - 1
      - 5
    session_history: code/_session_history.ipynb
