wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691814689.372691
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.9.17
      5: 0.15.8
      8:
      - 5
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
random_seed:
  desc: null
  value: 42
stratify_by:
  desc: null
  value: neighbourhood_group
rf_config:
  desc: null
  value: /Users/apple/Desktop/ranga_udacity/c3_project/nyc-rental-prices-predictions-ml-pipeline/outputs/2023-08-12/09-52-11/rf_config.json
max_tfidf_features:
  desc: null
  value: 30
output_artifact:
  desc: null
  value: random_forest_export
n_estimators:
  desc: null
  value: 100
max_depth:
  desc: null
  value: 100
min_samples_split:
  desc: null
  value: 4
min_samples_leaf:
  desc: null
  value: 3
n_jobs:
  desc: null
  value: -1
criterion:
  desc: null
  value: mae
max_features:
  desc: null
  value: 0.33
oob_score:
  desc: null
  value: true
