channels:
- conda-forge
dependencies:
- python=3.9.17
- pip<=23.2.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.24.4
  - pandas==2.0.3
  - psutil==5.9.5
  - scikit-learn==0.24.0
  - scipy==1.11.1
name: mlflow-env
